name: rl_gym
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - cudatoolkit=11.1.1
  - cudnn=8.1.0.77
  - python=3.9
  - pytorch=1.9.0=py3.9_cuda11.1_cudnn8_0
  - torchvision=0.10.0=py39_cu111
  - pip=21.1.2
  - pip:
    - pandas
    - plotly    
    # - scipy
    # - torch-summary
    - gym
    - gym[all]
    - pyvirtualdisplay
    - PyOpenGL
    - PyOpenGL-accelerate